version: 0.0
os: windows
files:
  - source: /source
    destination: C:\MyApp
hooks:
  BeforeInstall:
    - location: scripts/install.ps1
      timeout: 300
      runas: Administrator
  AfterInstall:
    - location: scripts/start.ps1
      timeout: 300
      runas: Administrator
  ApplicationStop:
    - location: scripts/stop.ps1
      timeout: 300
      runas: Administrator
